d = input('Digite algo: ')
print('A classe desse valor é', type(d))
print('Só tem espaços: ', d.isspace())
print('Só tem números:', d.isnumeric())
print('É um alfabetico: ', d.isalpha())
print('É um AlfaNúmerico', d.isalnum())
print('Está em MAIUSCULA: ', d.isupper())
print('Está em minuscula: ', d.islower())
print('Está Capitalizada: ', d.istitle())